version: '1'

services:
  backend:
    build:
      context: server
      dockerfile: Dockerfile
    container_name: go_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
      - minio

  db:
    image: postgres:13
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio_storage
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminadmin
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
  minio_data:
